spring:
  profiles:
    active:
      -  dog
      -  EN
      -  dev
guru:
  username: YmlUserName
  password: YmlPassword
  jdbcurl: YmlUrl
---
spring: prod
guru:
  username: YmlProdUserName
  password: YmlProdPassword
  jdbcurl: YmlProdUrl